current_profile: CQU
profiles:
  CQU:
    login: https://login.cqu.edu.cn:802/eportal/portal/login?callback=dr1004&user_account=,{device},{account}&user_password={password}&wlan_user_ip={ip}
    logout: https://login.cqu.edu.cn:802/eportal/portal/logout?callback=dr1006&wlan_user_ip={ip}
    unbind: https://login.cqu.edu.cn:802/eportal/portal/mac/unbind?callback=dr1005&user_account={account}&wlan_user_ip={ip}
user_info:
  account: xxxx
  device: '1'
  password: xxxxx

